
# API all users

GET {{host-url}}//users/allUsers
Content-Type: application/json

###

# API register User



POST {{host-url}}//registration
Content-Type: application/json

{

  "username": "Dmytro",
  "email": "kordfish@gmail.com",
  "password": "1111",
  "enabled": true,
  "role": "USER"

}


###

POST {{host-url}}//login
Content-Type: application/json

{
  "email": "kordfish@gmail.com",
  "password": "1111"
}

###
# API delete User

DELETE {{host-url}}//users/deleteUser/korish
Content-Type: application/json

#########################################################################

# API All courses

GET {{host-url}}//courses/all

###

# find tasks by course ID

POST {{host-url}}//courses/new
Content-Type: application/json

{
  "title": "Java Core Part 1",
  "titleDescription": "test",
  "userId": "c5c01a9b-f68d-4828-a429-031300a07595",
  "requirements": "english",
  "description": "lalala"
}

#########################################################################

# API All tasks

GET {{host-url}}//tasks/all

###

POST {{host-url}}//tasks/new
Content-Type: application/json

{
  "title": "Checking",
  "courseId": "f1bd69b7-7674-4800-853e-313a5b4a0b67"
}


###
POST {{host-url}}//tasks/uploadVideo/19dda7b5-c03f-42c5-a41d-132268eed3d1
#Content-Type: application/json

###