
# API all users

GET {{host-url}}//users
Content-Type: application/json

###

# API register User



POST {{host-url}}//registration
Content-Type: application/json

{
  "username": "Dmytro",
  "email": "korish@gmail.com",
  "password": "111"
}


###

POST {{host-url}}//login
Content-Type: application/json

{
  "email": "korish@gmail.com",
  "password": "111"
}

###
# API All courses

GET {{host-url}}//courses

###

# find tasks by course ID

POST {{host-url}}//courses/new
Content-Type: application/json

{
  "title": "Java2",
  "titleDescription": "test",
  "userId": "1a9d0a19-9236-40ae-b3df-26c6255dea37",
  "requirements": "english",
  "description": "lalala"
}

###
# API Delete course by id

DELETE {{host-url}}//courses/e2f9dad6-1eef-4bf7-9ce0-85eac3577379


#########################################################################

# API All tasks

GET {{host-url}}//tasks

###

POST {{host-url}}//tasks/new
Content-Type: application/json

{
  "title": "Checking",
  "courseId": "d0386a57-3513-4a7a-81a1-52c6cdf8c9e7"
}

