

# API all users

GET {{host-url}}//users/all

###

# Post User

POST {{host-url}}//users/registration
Content-Type: application/json

{

  "name": "test",
  "email": "testj",
  "password": "test123"
}

###

# API All courses

GET {{host-url}}//courses/all

###

# find tasks by course ID

POST {{host-url}}//courses/new
Content-Type: application/json

{
  "title": "Phyton",
  "titleDescription": "test",
  "userId": "0563aa22-2280-4849-a7e3-0dbe68e8f276",
  "requirements": "english",
  "description": "lalala"
}

###

# API All tasks

GET {{host-url}}//tasks/all

###

# post Task

POST {{host-url}}//tasks/new
Content-Type: application/json

{
  "title": "Overview2",
  "added": "2019-03-30T13:18:05.447+0000",
  "course": {
    "id": "11a41e80-b08b-4676-a49e-eafc48493e5d",
    "title": "Phyton",
    "titleDescription": "",
    "user": {
      "id": "71e93841-c910-472d-8633-60485e81e7cd",
      "name": "Danylo",
      "email": "dada",
      "password": "2d32m"
    },
    "requirements": "English",
    "description": "lalala",
    "created": "2019-03-30T13:18:05.428+0000"
  }
}

###





# find courses by user ID

GET {{host-url}}//courses/byUser/e0699c8e-b4d6-4ff3-a955-0ad70c538e73

###

# find tasks by course ID

GET {{host-url}}//tasks/byCourse/{CourseID}

###





###


